# config/packages/acseo_typesense.yml
acseo_typesense:
  # Typesense host settings
  typesense:
    url: '%env(resolve:TYPESENSE_URL)%'
    key: '%env(resolve:TYPESENSE_KEY)%'
  collections:
    books:
      entity: 'App\Entity\Book'
      fields:
        id:
          name: id
          type: primary
        title:
          name: title
          type: string
        sortable_id:
          entity_attribute: id             # Entity attribute name forced
          name: sortable_id                # Typesense field name
          type: int32
        serie:
          name: serie
          type: string
          optional: true
          facet: true
        summary:
          name: summary
          type: string
          optional: true
        serieIndex:
          name: serieIndex
          type: string
          optional: true
        extension:
          name: extension
          type: string
          facet: true
        authors:
          name: authors
          type: string[]
          facet: true
        tags:
          name: tags
          type: string[]
          facet: true
          optional: true
      default_sorting_field: sortable_id
      symbols_to_index: ['+', '#', '@', '_']
      token_separators: [' ', '-', "'"]
      finders:
        books_autocomplete:
          finder_parameters:
            query_by: title,serie,extension,authors,tags,summary
            limit: 16
            num_typos: 2