monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - proxy # Proxy logs are logged in the dedicated "proxy" channel when it exists


    handlers:
        main:
            type: rotating_file
            level: info
            channels: [ "!deprecation"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        proxy:
            type: stream
            path: "php://stdout"
            level: debug
            channels: ["proxy"]

        deprecation:
            type: stream
            channels: [deprecation]
            path: "%kernel.logs_dir%/deprecation.%kernel.environment%.log"
