monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists


    handlers:
        main:
            type: rotating_file
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            channels: [deprecation]
            path: "%kernel.logs_dir%/deprecation.%kernel.environment%.log"
