monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - kobo_proxy # Proxy logs are logged in the dedicated "proxy" channel when it exists
        - kobo_http # All request done on AbstractKoboController
        - kobo_sync # Log specific to Sync endpoint
        - kobo_kepubify # kepub conversion


    handlers:
        main:
            type: rotating_file
            level: info
            channels: [ "!deprecation"]
            max_files: 10

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!deprecation"]
        kobo:
            type: rotating_file
            level: debug
            channels: ["kobo_proxy","kobo_http", "kobo_sync", "kobo_kepubify"]
            path: "%kernel.logs_dir%/kobo.%kernel.environment%.log"
            max_files: 10

        deprecation:
            type: rotating_file
            channels: [deprecation]
            path: "%kernel.logs_dir%/deprecation.%kernel.environment%.log"
            max_files: 10
