twig:
    default_path: '%kernel.project_dir%/templates'


    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
      default_library_folder: '@App\Service\DefaultLibrary'
when@test:
    twig:
        strict_variables: true
