version: '3.8'

services:
  biblioteca:
    image: ghcr.io/biblioverse/biblioteca-docker:latest
    # build:
    #   context: .
    #   target: base
    entrypoint: ["/bin/sh", "-c" , "crontab /var/www/html/config/crontab.txt && apache2-foreground" ]
    ports:
      - "48480:8080"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - .composer:/home/.composer:cached
    stdin_open: true
    tty: true
    networks:
      - default
      - pontsun

  db:
    image: mariadb:10.10
    environment:
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    ports:
      - "49405:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - default

  typesense:
      image: typesense/typesense:0.26.0.rc46
      restart: on-failure
      ports:
        - 8983
        - "8108:8108"
      volumes:
        - searchdata:/data
      command: '--data-dir /data --api-key=xyz --enable-cors'

volumes:
  mariadb:
  searchdata:

networks:
  pontsun:
    external: true



