# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Tests

on: [push,pull_request]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typesense-version: [ 0.23.1 ]

    steps:
      - name: Start Typesense
        uses: jirevwe/typesense-github-action@v1.0.1
        with:
          typesense-version: ${{ matrix.typesense-version }}
          typesense-api-key: xyz
      - name: Curl Typesense
        run: sleep 10 && curl http://localhost:8108/health

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite
      - name: Execute tests
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: |
          bin/console doctrine:schema:create --env=test
          bin/console doctrine:schema:update --force --complete --env=test
          bin/console typesense:create --env=test
          composer test
