# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Tests

on: [push,pull_request]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        # Run Docker Compose Action
      - name: Copy .env.test.local
        run: |
          php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
          docker network create pontsun
      - name: Install Compose
        uses: ndeloof/install-docker-compose

      - name: Run docker-compose up
        run: docker-compose up -d

      - name: Install Composer Dependencies
        run: docker-compose exec biblioteca composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM Dependencies
        run: docker-compose exec biblioteca npm i

      - name: Build npm
        run: docker-compose exec biblioteca npm run build

      - name: Execute tests
        run: docker-compose exec biblioteca composer test

      - name: Run docker-compose down
        run: docker-compose down