# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Tests

on: [push,pull_request]

permissions:
  contents: read

jobs:
  biblioteca-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare env
        run: |
          php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
          touch .env.local && echo "APP_ENV=test" >> .env.local
          cp docker-compose.yml.test docker-compose.override.yml
          docker network create pontsun
          mkdir -p vendor var node_modules public/build public/books public/covers public/media 
          chmod -R 777 .

      - name: Install Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Run docker-compose up
        run: docker compose up -d

      - name: Install Composer Dependencies
        run: docker compose exec biblioteca composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM Dependencies
        run: docker compose exec biblioteca npm i

      - name: Build npm
        run: docker compose exec biblioteca npm run build

      - name: Prepare Database
        run: |
          docker compose exec biblioteca bin/console doctrine:database:create --env=test -n
          docker compose exec biblioteca bin/console doctrine:migrations:migrate --env=test -n
          docker compose exec biblioteca bin/console typesense:create --env=test
          docker compose exec biblioteca bin/console doctrine:fixtures:load --env=test --append -n

      - name: Execute tests
        run: docker compose exec biblioteca composer test

      - name: Coverage Report as Comment (Clover)
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: coverage.xml

      - name: Run docker-compose down
        run: docker compose down